### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg-docs#1]
Initial list of things to do to get properly started
- [x] Copy the existing English version
  - [x] copy the relevant images
  - [x] review the make file 
  - [x] review the conf.py file
- [x] Copy the existing French version
  - [x] review the make and conf.py file
- [x] Copy the existing Korean version
  - [x] review the make and conf.py file
  - [x] review layout.html to include Korean text (or explain how to do it)
- [ ] revise the css
- [x] revise the themes to replace the French/English link by an html select
  - [x] structure the path differently so that they can be tested locally as well as on the site
  - [x] change the order so that the current language is shown first (by default) - or use the selected attribute
- [x] create an appropriate .gitignore file to prevent savings commit to the build
- [ ] write  a document explaining how to add a new translation
  - [ ] include information about automatic importing of reeborg_xx.py docstrings
